export async function handleWhatsappErrorConsumer(data: any): Promise<void> {
  console.log('[Consumer] Erro recebido do WhatsApp:', data);
}
